name: deploy-event-bus

on:
  push:
    branches:
      - main
    paths:
      - 'event-bus/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd event-bus && docker build -t johnsachin/event-bus .
      - run: docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push johnsachin/event-bus
