name: tests

on:
  pull_request:
    paths:
      - 'moderation/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd moderation && npm install && npm run
